### ISSUE TITLE
libgmp.so.3 not found, convert fails

### ISSUE THREAD

**Issue by ivarvong** [Docverter/docverter#41]
I'm trying to deploy to Heroku. I followed the instructions. I had to bump the JRuby version (as per https://devcenter.heroku.com/articles/ruby-support#ruby-versions), so line 4 of the Gemfile is now:
`ruby '1.9.3', engine: 'jruby', engine_version: '1.7.21'`

When I make a call to `/convert`, I get an error in the Ruby app (using the docverter gem):

`Docverter API Error: command error: pandoc: error while loading shared libraries: libgmp.so.3: cannot open shared object file: No such file or directory (status: 500)`

My Heroku app's config:
```=== (redacted) Config Vars
BUILDPACK_URL:   https://github.com/ddollar/heroku-buildpack-multi.git
JAVA_OPTS:       -Xss512k -XX:+UseCompressedOops -Dfile.encoding=UTF-8
JRUBY_OPTS:      -Xcompile.invokedynamic=false
LANG:            en_US.UTF-8
LD_LIBRARY_PATH: /app/calibre/lib
PATH:            bin:/app/bin:/app/jruby/bin:/usr/bin:/bin:/app/calibre/bin
RACK_ENV:        production```

**Comment by samstickland** [comment]
+1

**Comment by 30f0fn** [comment]
I've run into a similar problem.  During an upgrade from cedar-10 to cedar-14 on heroku, pypandoc calls the pandoc command .convert, which breaks the build.

```
remote:        Collecting pypandoc==0.9.8 (from -r requirements.txt (line 39))
remote:          Downloading pypandoc-0.9.8.tar.gz
remote:            Complete output from command python setup.py egg_info:
remote:            pandoc: error while loading shared libraries: libgmp.so.3: cannot open shared object file: No such file or directory
remote:            Traceback (most recent call last):
remote:              File "<string>", line 20, in <module>
remote:              File "/tmp/pip-build-cOJLnQ/pypandoc/setup.py", line 6, in <module>
remote:                long_description = pypandoc.convert('README.md', 'rst')
remote:              File "pypandoc.py", line 94, in convert
remote:                outputfile=outputfile, filters=filters)
remote:              File "pypandoc.py", line 114, in _convert
remote:                from_formats, to_formats = get_pandoc_formats()
remote:              File "pypandoc.py", line 269, in get_pandoc_formats
remote:                txt = ' '.join(help_text[1:help_text.index('Options:')])
remote:            ValueError: 'Options:' is not in list
remote:            
remote:            ----------------------------------------
remote: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cOJLnQ/pypandoc
remote: 
remote:  !     Push rejected, failed to compile Multipack app
```

**Comment by samstickland** [comment]
I've completed a recompile of pandoc on Heroku, which should fix the
problem. I'm just having trouble making my new archive work with
.vendor_urls for some reason though. I'll post it here after I've figured
out what's wrong.

2015-08-26 18:44 GMT+01:00 30f0fn <notifications@github.com>:

**Comment by samstickland** [comment]
Well, I missed that up. When I try to use my new pandoc binary I get:

    2015-08-27T12:51:19.304632+00:00 app[web.1]: RuntimeError (pandoc: Could not find data file /app/my_new_software/share/x86_64-linux-ghc-7.8.4/pandoc-1.15.0.6/data/docx/[Content_Types].xml

so I clearly forgot to include all the necessary files in the binary. Heroku seems to have reset my dyno I used for building it so I've got to kick off another build. Last time it took several hours to complete.

**Comment by 30f0fn** [comment]
Darn!  Well, this sounds like the right idea.  The Heroku support people said

"cedar-10 included the libgmp3c2 package where the so in question was stored.
cedar-14 includes the libgmp10 package, which has a different version of the GNU MP library"

so the cedar upgrade must've broken some shared library dependencies of the pandoc binary.

Thanks for looking into this...

**Comment by samstickland** [comment]
OK, this is a little clumsily put together as it includes the entire output of the build, including manuals etc, but it does work.

https://s3-eu-west-1.amazonaws.com/hubbado-heroku-binaries/pandoc-1.15.0.6.tar.gz

**Comment by 30f0fn** [comment]
sweet!  thank you...  that fixed the problem perfectly.

**Comment by jonathankau** [comment]
Anyone know how to fix this error while running the server on a VPS? (DigitalOcean in particular)

**Comment by jonathankau** [comment]
Figured it out, for anyone else wondering how to fix this, enter your machine (either on Heroku or a VPS) and navigate to the `/app` folder.

Download and unzip the tar to some location on the machine. Then, copy the `/pandoc` folder into `/app` and copy the binary itself into `/app/bin`
